# Generated by Django 6.0.1 on 2026-02-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
